class ScannerStrings {
  const ScannerStrings._();

  static const String history = 'HISTORY';
  static const String noScansYet = 'No scans yet';
  static const String startScanningProducts = 'Start scanning products to see their impact on your gut health.';
  static const String scanResult = 'Scan Result';
  static const String nutrientLevels = 'Nutrient Levels';
  static const String cautions = 'Cautions';
  static const String productNotFound = 'Product not found';
  static const String rescanBarcode = 'Rescan Barcode';
  static const String enterManually = 'Enter Manually';
  static const String scanning = 'Scanning...';
  static const String analyzingProductInfo = 'Analyzing product...';
  static const String barcodeTip = 'Tip: Keep the barcode within the frame and ensure good lighting.';
  static const String allowCameraAccess = 'Allow Camera Access';
  static const String turnTorchOff = 'Turn Torch Off';
  static const String turnTorchOn = 'Turn Torch On';
  static const String switchCamera = 'Switch Camera';
  static const String enterBarcode = 'Enter Barcode';
  static const String searchProduct = 'Search Product';
  static const String restaurantMenuLabel = 'Restaurant Menu';
  static const String productBarcodeLabel = 'Product Barcode';
  static const String ingredientsLabel = 'Ingredients Label';
  static const String mealSnapLabel = 'Meal Snap';
  static const String productNotFoundAnalyzing = 'Analyzing...';
  static const String couldNotAnalyzeVision = 'Could not analyze image. Try again.';
  static const String productFoundAiFailed = 'Found product but analysis failed.';
  static const String failedToAnalyzeProduct = 'Failed to analyze product.';
  static const String noBarcodeDetected = 'No barcode detected.';
  static const String noBarcodeInGallery = 'No barcode found in gallery image.';
  static const String closeScanner = 'Close Scanner';
  static const String pickFromGallery = 'Pick from Gallery';
  static const String cameraAccessSubtitle = 'We need camera access to scan barcodes and analyze food images.';
  static const String openSettings = 'Open Settings';
  static const String capturePhoto = 'Capture Photo';
  static const String scanImageHero = 'Scan Image';
  static const String nutriScore = 'Nutri-Score';
  static const String nova = 'NOVA';
  static const String allergensLabel = 'Allergens';
  static const String additivesLabel = 'Additives';
  static const String betterSwapsLabel = 'Better Swaps';
  static const String productNotFoundMessage = 'We couldn\'t find this product in our database.';
  static const String errorAnalyzingProduct = 'Error analyzing product data.';
  static const String enterBarcodeHint = 'Enter 13-digit barcode';
  static const String enterBarcodeSubtitle = 'Manual Entry';
  static const String barcodeHelpText = 'Enter the barcode number found on the product packaging.';
  static const String tip = 'Tip';
  static const String nutritionFactsLabel = 'Nutrition Facts';
  static const String nutritionPer100g = 'Nutrition per 100g';
  static const String nutrientLevelsLabel = 'Nutrient Levels';
  static const String nutrientLevelsDisclaimer = 'Based on standard reference values.';
  static const String safetyCautions = 'Safety Cautions';
  static const String upgradeLabel = 'Upgrade';
  static const String pointsUnit = 'pts';
  static const String phase = 'PHASE';
  static const String cleanComposition = 'Clean Composition';
  static const String weeklyGutRecap = 'Weekly Gut Recap';
  static const String last7DaysReady = 'Your last 7 days are ready.';
  static const String loadingInitializingVision = 'Initializing Vision...';
  static const String loadingReadingIngredients = 'Reading ingredients...';
  static const String loadingIdentifyingTriggers = 'Identifying triggers...';
  static const String loadingMatchingGoals = 'Matching your goals...';
  static const String loadingSynthesizingInsights = 'Synthesizing insights...';
  static const String labelSavedItem = 'SAVED ITEM';
  static const String analyzeWithAi = 'Analyze with Intelligence';

  // --- Guided Scanner UX ---
  static const String barcodeGuidancePrimary = 'Center barcode in frame';
  static const String barcodeGuidanceSecondary = 'Keep the barcode steady.';
  static const String mealGuidancePrimary = 'Fit your meal inside the frame';
  static const String mealGuidanceSecondary = 'Make sure the full meal is visible.';
  static const String labelGuidancePrimary = 'Position the ingredients list inside the frame';
  static const String labelGuidanceSecondary = 'Keep the text clear and readable.';
  static const String ingredientsGuidancePrimary = 'Position ingredients list in frame';
  static const String ingredientsGuidanceSecondary = 'Make sure the entire list is visible.';
  static const String menuGuidancePrimary = 'Position menu in frame';
  static const String menuGuidanceSecondary = 'Fit the menu text inside the frame.';

  static const String stateSearching = 'Searching';
  static const String stateDetected = 'Detected';
  static const String stateLabelDetected = 'Label detected';
  static const String stateHoldSteady = 'Hold steady';
  static const String stateReady = 'Ready';
  static const String stateAnalyzing = 'Analyzing...';

  static const String errorTooFar = 'Move closer';
  static const String errorTooClose = 'Move back slightly';
  static const String errorBlurry = 'Hold steady';
  static const String errorTooDark = 'Move to better lighting';
  static const String errorPartiallyVisible = 'Fit the full label inside the frame';
  static const String errorTextNotReadable = 'Keep the ingredients text clear';

  // New
  static const String gutHealthImpact = 'GUT HEALTH IMPACT';
  static const String whatToWatch = 'WHAT TO WATCH';
  static const String clinicalAudit = 'CLINICAL AUDIT';
  static const String nutritionAnalytics = 'NUTRITION ANALYTICS';
  static const String productMetadata = 'PRODUCT METADATA';
  static const String expertSummary = 'EXPERT SUMMARY';
  static const String inflammatoryTrigger = 'Inflammatory trigger';
  static const String alert = 'ALERT';
  static const String caution = 'CAUTION';
  static String analyzedPer(String size) => 'Analyzed per $size';
}
